apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ksit-system

resources:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: ksit-controller-manager

images:
  - name: controller
    newName: kubestellar/integration-toolkit
    newTag: dev

namePrefix: dev-