apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo

resources:
  - ../../base

namePrefix: cluster2-

patches:
  - target:
      kind: Deployment
      name: demo-app
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
      - op: add
        path: /spec/template/metadata/labels/cluster
        value: cluster2

commonLabels:
  cluster: cluster2
  region: us-west
