apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ksit-system

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - rbac.yaml
  - deployment.yaml
  - service.yaml
  - crds.yaml # âœ… Use local CRDs file instead of relative paths

images:
  - name: controller
    newName: kubestellar/integration-toolkit
    newTag: latest
