apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ksit-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ksit-manager-role
subjects:
  - kind: ServiceAccount
    name: ksit-controller
    namespace: ksit-system
