apiVersion: v1
kind: Secret
metadata:
  name: argocd-token
  namespace: argocd
type: Opaque
stringData:
  # This will be replaced by the actual token from the command above
  token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhcmdvY2QiLCJzdWIiOiJhZG1pbjphcGlLZXkiLCJuYmYiOjE3Njk4NzAyNTEsImlhdCI6MTc2OTg3MDI1MSwianRpIjoiZTU5OTIxYjEtZTAyYS00MGU0LTk1YmYtOGJjMzFhYjMwYTZiIn0.GIYmtaen8tT-Ni0sEj_yeo9RnbohDB5B74EcvGOBleU"
