apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: ksit-demo-apps
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/namansh70747/kubestellar-integration-toolkit
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ksit-demo-workloads
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: ksit-demo-apps
  path: ./examples/multi-cluster-workloads
  prune: true
  targetNamespace: demo
