apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ksit-system

resources:
  - namespace.yaml
  - crd/bases/ksit.io_integrations.yaml
  - crd/bases/ksit.io_integrationtargets.yaml
  - manager/manager.yaml
  - manager/service.yaml
  - rbac/role.yaml
  - rbac/role_binding.yaml
  - rbac/service_account.yaml

images:
  - name: controller
    newName: kubestellar/integration-toolkit
    newTag: latest
