apiVersion: v2
name: ksit
description: KubeStellar Integration Toolkit - Multi-cluster DevOps tool health monitoring
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - kubernetes
  - multi-cluster
  - monitoring
  - devops
  - argocd
  - flux
  - prometheus
  - istio
home: https://github.com/namansh70747/kubestellar-integration-toolkit
sources:
  - https://github.com/namansh70747/kubestellar-integration-toolkit
maintainers:
  - name: Naman Sharma
    email: namansh70747@gmail.com
icon: https://raw.githubusercontent.com/namansh70747/kubestellar-integration-toolkit/main/docs/logo.png
