apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ksit-multi-cluster-apps
  namespace: flux-system
  labels:
    app.kubernetes.io/name: flux-kustomization
spec:
  interval: 10m0s
  path: "./clusters"
  prune: true
  sourceRef:
    kind: GitRepository
    name: ksit-multi-cluster-repo
  timeout: 3m0s
  retryInterval: 2m0s
  validation: client
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      namespace: default
      name: '*'